//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeMAkerFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class referenceTable
    {
        public int r_id { get; set; }
        public int resume_id { get; set; }
        public string teacher_name { get; set; }
        public string teacher_email { get; set; }
        public Nullable<int> teacher_phone { get; set; }
    
        public virtual profileTable profileTable { get; set; }
    }
}
