//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeMAkerFinal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ResumeMakerDatabaseEntities : DbContext
    {
        public ResumeMakerDatabaseEntities()
            : base("name=ResumeMakerDatabaseEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<educationTable> educationTables { get; set; }
        public virtual DbSet<examTable> examTables { get; set; }
        public virtual DbSet<extraCurricularTable> extraCurricularTables { get; set; }
        public virtual DbSet<profileTable> profileTables { get; set; }
        public virtual DbSet<referenceTable> referenceTables { get; set; }
        public virtual DbSet<skillsSetTable> skillsSetTables { get; set; }
        public virtual DbSet<skillsTable> skillsTables { get; set; }
        public virtual DbSet<toolsExpertiseLevel> toolsExpertiseLevels { get; set; }
    }
}
